added security check to workflow

diff --git a/.github/workflows/strict-lint.yaml b/.github/workflows/strict-lint.yaml
--- a/.github/workflows/strict-lint.yaml
+++ b/.github/workflows/strict-lint.yaml
@@ -27,6 +27,17 @@ jobs:
       - name: install all Dependencies
         run: npm ci
 
+      - name: Run security audit
+        run: npm audit
+        continue-on-error: true
+        id: security-audit
+
+      - name: Check for security vulnerabilities
+        if: steps.security-audit.outcome == 'failure'
+        run: |
+          echo "Security vulnerabilities found. Failing the workflow."
+          exit 1  
+
       - name: Run ESLint test
         run: npm run lint:strict
         continue-on-error: true
